export const JobData=[
    {
        "id": 1,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
    {
        "id": 2,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
    {
        "id": 3,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
    {
        "id": 4,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
    {
        "id": 5,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
    {
        "id": 6,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
    {
        "id": 7,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
    {
        "id": 8,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
    {
        "id": 9,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
    {
        "id": 10,
        "title":"Php and Laravel Developer",
        "status": "New",
        "remark": "Long term project",
        "salary": "~¥ 500000/month",
        "media": "Subcontacting",
        "area": "Japan City",
    },
]